# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c230dc81db7475b2d59dba30249e22ba6f61e78473043c3e1689028108db5d41b5c6f0da55c36cf9000587b6f3e21b33d6816715df7e37c2b03be83fe472a9f

test:
  secret_key_base: 683747f6f7a05372771c9b7c07ff52a200a687b7bd253ef3dc82932aaf5e614d3b2aa0c050f3f29df10ab46815ef819c34aee010abb29414e8667486db58f0d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
